mqtt:
  broker: your.mqtt.ip.address
  port: 1883
  client_id: home-assistant-1
  keepalive: 60
  username: YOURUSERNAME
  password: YOURPASSWORD
  
sensor:
  - platform: mqtt
    state_topic: "GarDoor/temperature"
    name: "Garage Temperature"
    qos: 0
    unit_of_measurement: '°C'

  - platform: mqtt
    state_topic: "GarDoor/humidity"
    name: "Garage Humidity"
    qos: 0
    unit_of_measurement: '%'
   
  - platform: mqtt
    name: "Garage Door Distance" 
    state_topic: "GarDoor/1/status"
    unit_of_measurement: 'cm'
    value_template: "{{value_json.distance}}"
    availability_topic: "GarDoor/availability"
    payload_available: "online"
    payload_not_available: "offline"
    icon: "mdi:garage"
    json_attributes_topic: "GarDoor/1/status"
   
  - platform: mqtt
    name: "Car Distance" 
    state_topic: "GarDoor/2/status"
    unit_of_measurement: 'cm'
    value_template: "{{value_json.distance}}"
    availability_topic: "GarDoor/availability"
    payload_available: "online"
    payload_not_available: "offline"
    icon: "mdi:car"
    json_attributes_topic: "GarDoor/2/status"
    
  - platform: mqtt
    name: "Wifi GarDoor NodeMCUv2"
    state_topic: "GarDoor/ESPtoMQTT"
    unit_of_measurement: 'dB'
    value_template: "{{value_json.rssi}}"
    availability_topic: "GarDoor/availability"
    payload_available: "online"
    payload_not_available: "offline"
    icon: "mdi:wifi"
    json_attributes_topic: "GarDoor/ESPtoMQTT"

binary_sensor:
  - platform: mqtt
    name: "Car Presence"
    state_topic: "GarDoor/2/status"
    payload_on: "true"
    payload_off: "false"
    availability_topic: "GarDoor/availability"
    payload_available: "online"
    payload_not_available: "offline"
    qos: 0
    device_class: occupancy
    value_template: '{{value_json.occupied}}'
    
  - platform: mqtt
    name: "Garage Door Status"
    state_topic: "GarDoor/1/status"
    payload_on: "open"
    payload_off: "closed"
    availability_topic: "GarDoor/availability"
    payload_available: "online"
    payload_not_available: "offline"
    qos: 0
    device_class: opening
    value_template: '{{value_json.status}}'
    
  - platform: mqtt
    name: "GarDoor Controller"
    state_topic: "GarDoor/availability"
    payload_on: "online"
    payload_off: "offline"
    device_class: connectivity
  
  - platform: mqtt
    name: "GarDoor Blynk"
    state_topic: "GarDoor/blynkavailability"
    payload_on: "blynkon"
    payload_off: "blynkoff"
    device_class: connectivity

cover:
  - platform: mqtt
    name: "Garage Door"
    state_topic: "GarDoor/1/status/value"
    command_topic: "GarDoor/1/action"
    availability_topic: "GarDoor/availability"
    qos: 0
    optimistic: false
    retain: false
    payload_open: "OPEN"
    payload_close: "CLOSE"
    payload_stop: "STATE"
    state_open: "open"
    state_closed: "closed"
    payload_available: "online"
    payload_not_available: "offline"
    device_class: garage

automation:
  #Make GarDoor Blynk connection unavailable if GarDoor becomes unavailable
  - alias: 'GarDoor Blynk unavailable'
    trigger:
      platform: state
      entity_id:  binary_sensor.gardoor_controller
      from: 'on'
      to: 'off'
    action:
      service: mqtt.publish
      data:
        topic: GarDoor/blynkavailability
        payload: "blynkoff"
        qos: 0
        retain: true        
   
  - alias: 'Update garage door/car state on startup'
    trigger:
      - platform: homeassistant
        event: start
    action:
      - service: mqtt.publish
        data:
          topic: GarDoor/1/action
          payload: "STATE"
   
  - alias: 'Close garage door if open for longer than 30 minutes'
    trigger:
      - platform: state
        entity_id: cover.garage_door
        to: "open"
        for:
         minutes: 30
    action:
      - service: cover.close_cover
        entity_id: cover.garage_door
